<div class="container">
    <div class="row clearfix">
        <div class="col-md-2 column"></div>
        <div class="col-md-8 column">
            <br>
            <pre>
                <h6>Travel hunter never stop !</h6>
                <h6>Do you wanna travel ?</h6>
                <h6>Do you need partners ?</h6>
                <h6>Do you wanna know the traces of travelers ?</h6>
                <h6>Then join us !</h6>
                <h6>You will enjoy yourself here !</h6>
                <h6>Remember !</h6>
                <h6>Travel hunter never stop !</h6>
                <h6>Travel Hunter : Chu Mingjun</h6>
                <img src="/images/user_img/img_default/default.png">

            </pre>


        </div>
        <div class="col-md-2 column"></div>
    </div>

</div>