<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" media="screen" href="/css/header.css"/>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
<!--    <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">-->
    <link href="http://pingendo.github.io/pingendo-bootstrap/themes/default/bootstrap.css" rel="stylesheet" type="text/css">

    <link href="/css/flat-ui.css" rel="stylesheet">

    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script src="/js/jquery.tablesorter.js"></script>
    <script src="/js/jquery.datePicker.js"></script>
    <script src="/js/stickUp.js"></script>
    <script src="/js/my-jQuery.js"></script>
    <script src="/js/jquery.googlemap.js"></script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBAzlvERdn7z0oRAMQIw4ks14KzIok7GRI"></script>


    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


    <title>Travel Hunter</title>
</head>
<body>
    <?php
    include "header.phtml";
    ?>
    <?=$this->layout()->content;?>
    <?php
    include "footer.phtml";
    ?>
</body>
</html> 