
<div class="container">





    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-8">
            <form class="form-horizontal" role="form" action="/login/loginprocess" method="post" onsubmit="return check_user_info();">




                <div class="form-group">
                    <label for="email_address" class="col-md-4 control-label">Email address</label>
                    <div class="col-md-5">
                        <input type="text" class="form-control" id="email_address" name="email_address"
                               placeholder="Please enter your email address">
                    </div>
                </div>






                <div class="form-group">
                    <label for="password" class="col-md-4 control-label">Enter password</label>
                    <div class="col-md-5">
                        <input type="password" class="form-control" id="password" name="password"
                               placeholder="Please enter password">
                    </div>
                </div>








                <div class="form-group">
                    <label for="captcha_code" class="col-md-4 control-label">Captcha</label>
                    <div class="col-md-5">
                        <input type="text" class="form-control" id="captcha_code" name="captcha_code"
                               placeholder="Please enter captcha">
                    </div>
                    <label class="col-md-3 control-label" id="captcha_code_info"></label>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                    </div>
                    <div class="col-md-5">
                        <img src="" class="col-md-7" alt="Get Captcha" id="captcha_img">
                    </div>
                </div>






                <div class="form-group">
                    <div class="col-md-4">
                    </div>
                    <div class="col-md-6">
                        <button type="submit" class="btn btn-primary col-md-offset-0">Log in</button>
                        <button type="reset" class="btn btn-primary col-md-offset-5" id="reset">Reset</button>
                    </div>
                </div>


            </form>

        </div>
        <div class="col-md-2">
        </div>
    </div>
    </div>
