<div class="container">


    <!-- **********************注册项目********************** -->


    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-8">
            <?php
            echo $this->feedback . "<br>";
            echo "If the page hasn't jumped so far, please enter " . "<a href='" . $this->goUrl . "'>here</a>" ;

            ?>
            <script type="text/javascript">
                setTimeout(function(){
                    window.location.href ='<?= $this->goUrl?>';
                },5000);
            </script>

        </div>
        <div class="col-md-2">
        </div>
    </div>
</div>
